#!/usr/bin/env python

from pprint import pprint
import os
import sys

from rbtools.api.client import RBClient

rb_url = os.getenv('RB')
if not rb_url:
  print "Couldn't get RB url from `env` -- set and export RB!"
  sys.exit(1)

client = RBClient(rb_url)
root = client.get_root()
pprint(root['payload'])
