#!/usr/bin/env bash

curl "https://reviewboard.twitter.biz/r/$1/diff/raw/" > "$HOME/tmp/$1.patch"

RET="$?"
if [ "$RET" -eq 0 ] ; then
  mv "$HOME/tmp/$1.patch" "$HOME/downloads/"
else
  exit $RET
fi


