#!/bin/bash

BRANCH="git-review/branches/$1"

echo "stashing changes.."
git st
git stash

git checkout master
git pull
git branch -l | grep -q "${BRANCH}" && git branch -D "${BRANCH}"

getrb "$1"
git checkout -b "${BRANCH}"
patch -p1 < "$HOME/downloads/${1}.patch"

FILES=($(git st --porcelain | awk {'print $2'} | grep -v '\.rej$' | grep -v '\.orig$'))
git add "${FILES[@]}"
git ci -m "git-recheckout ${1}"
git review set "$1"
