#!/bin/bash

DELETE="$1"
ME="$(git config user.name)"

for b in $(git for-each-ref --format=' %(authorname) %09 %(refname)' --sort=authorname  | grep -i "${ME}" | awk {'print $3'} | grep -v master  | grep -v 'refs/tags' | sed 's|refs/remotes/origin/||' | grep -v on-prem- ) ; do
  echo "branch: $b"

  if ! [ z"${DELETE}" = z ] ; then
    git push origin :$b
  fi
done
