#!/usr/bin/env bash
#
# Use meld to diff against something in in the paste-buffer
#
# If the first arg is a file, that will be used.
# Otherwise, meld opens with two empty files

MELDTMP=$(mktemp -d) || { RC=$?; echo "mktemp failed"; exit $RC; }
echo "MELDTMP='$MELDTMP'"

if [ -f "$1" ] ; then
  A="$1"
else
  A="${MELDTMP}/meldpaste_a"
  > "$A"
fi

B="${MELDTMP}/meldpaste_b"
> "$B"

meld "$A" "$B"

rm -rf "${MELDTMP}"

