#!/usr/bin/env bash
#
# Use meld to diff against something in in the paste-buffer
#
# If the first arg is a file, that will be used.
# Otherwise, meld opens with two empty files

mkdir -p "${HOME}/tmp"

if [ -f "$1" ] ; then
  B="$1"
else
  B="${HOME}/tmp/b"
  [ -f "$B" ] && rm "$B"
  touch "$B"
fi

A="${HOME}/tmp/a"
[ -f "$A" ] && rm "$A"
touch "$A"

meld "$A" "$B"
