#!/bin/bash
#
# Technically not a PR, but the diff view which leads to one
#

COMPARE_BRANCH="$1"
BRANCH="$2"

# get the remote as a url (even if it's git@foo.com/bar.git)
REMOTE="$(git remote -v  | grep origin | grep push | awk '{print $2}')"
if [[ "${REMOTE}" == "git@"* ]] ; then
  REMOTE="https://$(echo "${REMOTE}" | sed 's|\.git$||' | sed 's|:|/|' | sed 's|^git@||')"
else
  REMOTE="$(echo "${REMOTE}" | sed 's|\.git$||')"
fi

if [[ "${REMOTE}" == *github.com* ]] ; then
  URL="${REMOTE}/compare/${COMPARE_BRANCH}...${BRANCH}?expand=1"
  echo "${URL}"

  generic_open "${URL}"
fi
