#!/usr/bin/env bash
#
# Open all files modified in HEAD

. bash_safe_mode

files=($(git diff-tree --no-commit-id --name-only -r HEAD))

cd "$(git rev-parse --show-toplevel)" || exit 1

vim -p "${files[@]}"
