#!/bin/bash

XBMCLOGDIR="$HOME/.xbmc/temp"

LOGFILE="$HOME/logs/xbmc-restarted/xbmc-restarted.log"
LOGDIR="$(dirname "${LOGFILE}")"
mkdir -p "${LOGDIR}" 

echo "$(nicedatetime): xbmc-restart called" >> $LOGFILE

if ! [ $(pgrep -c xbmc.bin) -eq 0 ] ; then
	for SIG in INT TERM HUP KILL ; do
		PID=$(pgrep xbmc.bin)
		if ! [ x$PID = x ] ; then
			echo "$(nicedatetime): kill -$SIG $PID" >> $LOGFILE
			kill -${SIG} ${PID}
			sleep 5
		fi
	done

	if ! [ $(pgrep -c xbmc.bin) -eq 0 ] ; then
		echo "$(nicedatetime): FAILED TO KILL XBMC" >> $LOGFILE
		exit 1
	else
		echo "$(nicedatetime): Killed xbmc" >> $LOGFILE
	fi
else
	echo "$(nicedatetime): xbmc wasn't running" >> $LOGFILE
fi

for i in xbmc.log xbmc.old.log ; do 
	xbmc_log="${XBMCLOGDIR}/${i}"
	if [ -f "$xbmc_log" ] ; then
		mv "$xbmc_log" "$LOGDIR/${DATE}-${i}"
	fi
done

DISPLAY=:0 xbmc -fs & &> /dev/null 
