#!/bin/bash

XBMCLOGDIR="$HOME/.xbmc/temp"

LOGFILE="$HOME/logs/xbmc-restarted/xbmc-restarted.log"
LOGDIR="$(dirname "${LOGFILE}")"
mkdir -p "${LOGDIR}"

echo "$(nicedatetime): xbmc-restart called" >> $LOGFILE

strings=( "/usr/lib64/xbmc/xbmc.bin" "/bin/sh /usr/bin/xbmc" "/usr/bin/python2.7 /usr/share/xbmc/FEH.py" )

proc_count() {
    echo $(pgrep -c -f "$*")
}

xbmc_exists() {
    for str in "${strings[@]}" ; do
        if ! [ $(proc_count "$str") -eq 0 ] ; then
            return 0
        fi
    done
    return 1
}

for str in "${strings[@]}" ; do
    for SIG in SIGINT SIGTERM SIGHUP SIGKILL ; do
        if ! [ $(proc_count ${str}) -eq 0 ] ; then
            pkill -f "${str}" --signal $SIG
            sleep 2
        fi
    done
done

if [ $(xbmc_exists) ] ; then
    echo "$(nicedatetime): FAILED TO KILL XBMC" >> $LOGFILE
    exit 1
else
    echo "$(nicedatetime): Killed xbmc" >> $LOGFILE
fi

for i in xbmc.log xbmc.old.log ; do
	xbmc_log="${XBMCLOGDIR}/${i}"
	if [ -f "$xbmc_log" ] ; then
        mv "$xbmc_log" "$LOGDIR/$(nicedatetime)-${i}"
	fi
done

DISPLAY=:0 xbmc -fs & &> /dev/null
